services:
  _defaults:
    public: true

  # Repository
  axelweb.awcontentfeed.repository.content_feed_item:
    class: 'Axelweb\AwContentFeed\Repository\ContentFeedItemRepository'

  # Services
  axelweb.awcontentfeed.service.metadata_fetcher:
    class: 'Axelweb\AwContentFeed\Service\MetadataFetcherService'

  # Content Feed Item form type
  axelweb.awcontentfeed.form.type.content_feed_item:
    class: 'Axelweb\AwContentFeed\Form\ContentFeedItemFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  # Content Feed Item form data provider
  axelweb.awcontentfeed.form.content_feed_item_form_data_provider:
    class: 'Axelweb\AwContentFeed\Form\ContentFeedItemFormDataProvider'
    arguments:
      - '@axelweb.awcontentfeed.repository.content_feed_item'
      - null

  # Content Feed Item form data handler
  axelweb.awcontentfeed.form.content_feed_item_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@axelweb.awcontentfeed.form.content_feed_item_form_data_provider'
      - 'Axelweb\AwContentFeed\Form\ContentFeedItemFormType'
      - 'AwContentFeed'
